// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_sztNXMjyGfmVQGYVgIEaWERHWLhHwY',
    appId: '1:414859422297:web:c0c35f0818442e014e9f48',
    messagingSenderId: '414859422297',
    projectId: 'glidixtaskmngr',
    authDomain: 'glidixtaskmngr.firebaseapp.com',
    storageBucket: 'glidixtaskmngr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFoen0U8MgvG6YFuLpvQdOFvTzJXpucnE',
    appId: '1:414859422297:android:568fa36c4aab31de4e9f48',
    messagingSenderId: '414859422297',
    projectId: 'glidixtaskmngr',
    storageBucket: 'glidixtaskmngr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-T6RCWuq1r2Mv612P538RKgVrpKt5Sdo',
    appId: '1:414859422297:ios:c6a25ea2db3a55c44e9f48',
    messagingSenderId: '414859422297',
    projectId: 'glidixtaskmngr',
    storageBucket: 'glidixtaskmngr.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-T6RCWuq1r2Mv612P538RKgVrpKt5Sdo',
    appId: '1:414859422297:ios:c6a25ea2db3a55c44e9f48',
    messagingSenderId: '414859422297',
    projectId: 'glidixtaskmngr',
    storageBucket: 'glidixtaskmngr.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-_sztNXMjyGfmVQGYVgIEaWERHWLhHwY',
    appId: '1:414859422297:web:a5f0dccf2ed42d664e9f48',
    messagingSenderId: '414859422297',
    projectId: 'glidixtaskmngr',
    authDomain: 'glidixtaskmngr.firebaseapp.com',
    storageBucket: 'glidixtaskmngr.firebasestorage.app',
  );
}
